FROM node:16-alpine as client

WORKDIR /usr/app/client
COPY client/yarn.lock ./

RUN yarn install
COPY client ./

RUN yarn build

FROM node:16-alpine
ENV NODE_ENV=production
ENV PORT=8080
ENV MONGO_URI=mongodb://mongo:27017/replay
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY --from=client /usr/app/client/build/ ./client/build

WORKDIR /usr/src/app/server/
COPY server/package*.json ./
RUN npm install -qy
COPY server/ .

ENV PORT 8080

EXPOSE 8080

CMD ["npm", "start"]
