version: "3.4"

services:
  server:
    image: app-server
    container_name: app-node-server
    restart: always
    depends_on:
      - mongo
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    environment:
      NODE_ENV: development
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9001:9001"
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    volumes:
      - data-volume:/data/db
    ports:
      - 27027:27017
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: app-client
    container_name: app-react-client
    volumes:
      - ./client/:/usr/app
      - /usr/src/app/node_modules
    command: yarn start
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local

networks:
  app-network:
    driver: bridge
