version: "3.4"

services:
  collector:
    image: collector
    restart: always
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - collector-vol:/usr/src/app
    ports:
      - 9001:9001
    networks:
      - collectornetwork

  mongodb:
    image: mongo
    restart: always
    volumes:
      - collectordb-vol:/data/db
    ports:
      - 27027:27017
    networks:
      - collectornetwork

volumes:
  collector-vol:

  collectordb-vol:

networks:
  collectornetwork:
    driver: bridge
