version: "3.4"

services:
  collector:
    image: collector
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - collector-vol:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - collectornetwork
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]

  mongodb:
    image: mongo
    restart: always
    volumes:
      - collectordb-vol:/data/db
    ports:
      - 27027:27017
    networks:
      - collectornetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - collectornetwork

volumes:
  collector-vol:

  collectordb-vol:

networks:
  collectornetwork:
    driver: bridge
